### ISSUE TITLE
all img/people aren't 220x220 (or even square)

### ISSUE THREAD

**Issue by Jim-Holmstroem** [Stockholm-AI/stockholm-ai#192]
Taras is one example

**Comment by Jim-Holmstroem** [comment]
related to https://github.com/Stockholm-AI/stockholm-ai/issues/77

**Comment by ycpei** [comment]
so a fix would be to crop (if not square) and resize all of them to 220x220?

**Comment by Jim-Holmstroem** [comment]
yes, I think its only Taras image that is not conforming to 220x220
